virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-pyopencl
language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.5"
script: "PYOPENCL_CTX=':' ./test.py"
